version: '2'
services:

    # our web application
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        volumes:
            - ./www:/var/www
        working_dir: /var/www
        environment:
            - DB_HOST=database
            - REDIS_HOST=redis
    nginx:
        build:
            context: ./
            dockerfile: nginx.dockerfile
        volumes:
            - ./www/public:/var/www/public
        ports:
            - 80:80

    # mysql database
    database:
        image: mysql
        environment:
          - "MYSQL_ROOT_PASSWORD=123456"
          - "MYSQL_DATABASE=blogs"
          - "MYSQL_USER=root"
          - "MYSQL_PASSWORD=123456"